database:
  user: "your_username"
  password: "your_password"
  host: "localhost"
  database: "salmodb"
  collection: "player_data"
  port: 27017
  thread-pool: 4
  connect-timeout-seconds: 3
  read-timeout-seconds: 2

spawn:
  world: world
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

cooldowns: # Cooldown times in seconds
  feed-cooldown: 10
  near-cooldown: 5

near:
  distance: 20.0 # Distance in blocks to consider "near"