mongodb:
  uri: "mongodb://172.18.0.1:27017"
  database: "salmobox"

spawn:
  world: world
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

cooldowns: # Cooldown times in seconds
  feed-cooldown: 10
  near-cooldown: 5

near:
  distance: 20.0 # Distance in blocks to consider "near"