name: SalmoBoxPlugin
version: '1.0'
main: net.salmo.SalmoBoxPlugin
description: BoxPvP core plugin for SalmoBox server.
api-version: '1.20'
authors: [Rud]

dependencies:
  server:
    PlaceHolderAPI:
      load: BEFORE
      required: false
      join-classpath: false