name: SalmoBoxCore
version: '1.0'
main: net.salmo.SalmoBoxPlugin
description: BoxPvP core plugin for SalmoBox server.
api-version: '1.20'
authors: [Rud]
website: https://github.com/SalmoBox-Network/

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false